debug: true
logging:
  file: logs/hongkongbuseta.log
  level:
    org:
      hibernate: ERROR
      springframework:
        web: WARN
server:
  port: ${PORT:5000}
feign:
  httpclient:
    disableSslValidation: true
    enabled: false
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
spring:
  datasource:
    hikari:
      maximumPoolSize: 5
    password: ${JDBC_DATABASE_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    url: ${JDBC_DATABASE_URL}&createDatabaseIfNotExist=true
    username: ${JDBC_DATABASE_USERNAME}
  devtools:
    livereload:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      connection:
        provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false